/* eslint-disable import/no-extraneous-dependencies */
import * as fs from "fs";
import * as path from "path";
import { defineConfig, type ViteDevServer } from "vite";
import { globSync } from "glob";

const writeProjectsHTML = () => {
  const projectsDir = path.join(process.cwd(), "projects");
  if (!fs.existsSync(projectsDir)) return "";
  // Empty session: the viewer with no ?model= params — load IFC files from
  // the UI (Add IFC…) instead of preloading them on disk.
  let links = `<a style="width: fit-content;" href="./projects/viewer.html">New empty session</a>\n`;
  const entries = fs.readdirSync(projectsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const projectDir = path.join(projectsDir, entry.name);
    const ifc = fs
      .readdirSync(projectDir)
      .find((file) => file.toLowerCase().endsWith(".ifc"));
    if (!ifc) continue;
    let title = entry.name;
    const titleFile = path.join(projectDir, "project.title");
    if (fs.existsSync(titleFile)) {
      const custom = fs.readFileSync(titleFile, "utf8").split("\n")[0].trim();
      if (custom) title = custom;
    }
    const model = encodeURIComponent(`${entry.name}/${ifc}`);
    links += `<a style="width: fit-content;" href="./projects/viewer.html?model=${model}&title=${encodeURIComponent(title)}">${title}</a>\n`;
  }
  // The gallery is generated by external tooling and is optional — only link
  // to it when it actually exists.
  if (fs.existsSync(path.join(projectsDir, "index.html"))) {
    links += `<a style="width: fit-content;" href="./projects/">All projects</a>\n`;
  }
  return `<h3>Projects</h3>\n${links}`;
};

const writeIndexHTML = () => {
  let links: string = "";
  const examplePaths = globSync("packages/**/src/**/example.html");
  for (const examplePath of examplePaths) {
    const directory = path.dirname(examplePath);
    const packageNameMatch = directory.match(/packages[\\\/]([^\\\/]+)/);
    if (!(packageNameMatch && packageNameMatch.length > 1)) continue;
    const packageName = packageNameMatch[1];
    const exampleName = path.basename(directory);
    links += `<a style="width: fit-content;" href="./${examplePath}">${packageName}/${exampleName}</a>\n`;
  }
  const index = `
  <!DOCTYPE html>
  <html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Examples Index</title>
    <style>
      * {
        margin: 0;
      }
  
      html {
        font-family: sans-serif;
      }
  
      body {
        padding: 1rem;
      }
    </style> 
  </head>
  
  <body>
    <div style="display: flex; flex-direction: column; gap: 1rem;">
      ${writeProjectsHTML()}<h3>Choose an example</h3>
      ${links}
    </div>
  </body>
  
  </html>
      `;
  fs.writeFileSync("./index.html", index);
};

const createIndex = () => ({
  name: "create-index",
  configureServer(server: ViteDevServer) {
    // fs.watch("./packages", { recursive: true }, writeIndexHTML);
    writeIndexHTML();
    // Projects are added and removed by external tooling — rebuild the home
    // page so new IFCs show up in the list without restarting the server.
    const projectsDir = path.join(process.cwd(), "projects");
    server.watcher.add(projectsDir);
    const onProjectsChange = (file: string) => {
      if (!file.startsWith(projectsDir)) return;
      writeIndexHTML();
    };
    server.watcher.on("add", onProjectsChange);
    server.watcher.on("change", onProjectsChange);
    server.watcher.on("unlink", onProjectsChange);
  },
});

export default defineConfig({
  plugins: [createIndex()],
  resolve: {
    // Workspaces install their own copy of three; without dedupe the dev
    // server serves two or three instances and three.js prints the
    // "Multiple instances of Three.js being imported" warning.
    dedupe: ["three"],
  },
});
